name: Minimal Reusable 4

on:
  workflow_call:
    inputs:
      curseforge-id:
        required: false
        type: string
      wago-id:
        required: false
        type: string
    secrets:
      CF_API_KEY:
        required: false
      WAGO_API_TOKEN:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "test ohne checkout"
