name: Minimal Reusable 3

on:
  workflow_call:
    inputs:
      curseforge-id:
        required: false
        type: string
      wago-id:
        required: false
        type: string
    secrets:
      CF_API_KEY:
        required: false
      WAGO_API_TOKEN:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Build packager args
        id: args
        run: |
          ARGS=""
          if [ -n "${{ inputs.curseforge-id }}" ]; then ARGS="$ARGS -p ${{ inputs.curseforge-id }}"; fi
          if [ -n "${{ inputs.wago-id }}" ]; then ARGS="$ARGS -a ${{ inputs.wago-id }}"; fi
          echo "args=$ARGS" >> "$GITHUB_OUTPUT"

      - name: Show args
        run: echo "Args waeren ${{ steps.args.outputs.args }}"
